package com.example.robotarm

import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import com.example.robotarm.ui.theme.RobotArmTheme // Make sure this matches your actual package name

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge() // Enables full screen (draw behind status bar)
        setContent {
            // Apply the default theme generated by Android Studio
            RobotArmTheme {
                var currentScreen by remember { mutableStateOf("menu") }
                when (currentScreen) {
                    "menu" -> RobotArmMenu(
                        onObjectTrackingClick = { currentScreen = "tracking" },
                        onColorTrackingClick = { /* TODO */ }
                    )
                    "tracking" -> ObjectTrackingScreen(
                        onBack = { currentScreen = "menu" }
                    )
                }
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class) // Needed for TopAppBar in Material3
@Composable
fun RobotArmMenu(
    onObjectTrackingClick: () -> Unit,
    onColorTrackingClick: () -> Unit
) {
    val context = LocalContext.current

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Robot Arm Controller") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                    titleContentColor = MaterialTheme.colorScheme.onPrimaryContainer
                )
            )
        }
    ) { innerPadding ->
        // This Column holds the buttons in the center of the screen
        Column(
            modifier = Modifier
                .padding(innerPadding) // Respect the TopAppBar space
                .fillMaxSize()
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {

            Text(
                text = "Select Mode",
                style = MaterialTheme.typography.headlineMedium,
                color = MaterialTheme.colorScheme.primary
            )

            Spacer(modifier = Modifier.height(32.dp))

            // --- Button 1: Object Tracking ---
            MenuButton(
                text = "Object Tracking",
                onClick = onObjectTrackingClick
            )

            Spacer(modifier = Modifier.height(16.dp))

            // --- Button 2: Color Tracking ---
            MenuButton(
                text = "Color Tracking",
                onClick = {
                    // TODO: Navigate to Color Tracking Screen
                    Toast.makeText(context, "Color Tracking Selected", Toast.LENGTH_SHORT).show()
                }
            )
        }
    }
}

// A reusable Composable button to keep the code clean
@Composable
fun MenuButton(text: String, onClick: () -> Unit) {
    Button(
        onClick = onClick,
        modifier = Modifier
            .fillMaxWidth() // Make button span the width
            .height(56.dp),   // Make it tall and touch-friendly
        elevation = ButtonDefaults.buttonElevation(8.dp)
    ) {
        Text(text = text, fontSize = 18.sp)
    }
}

//@Preview(uiMode = android.content.res.Configuration.UI_MODE_NIGHT_YES)
//@Composable
//fun DarkModePreview() {
//    RobotArmTheme {
//        RobotArmMenu()
//    }
//}